// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoVQ4DzNakx1pNU9BgdnPhTO5oUMfvh58',
    appId: '1:93036228074:web:936247e2bbf76ad13fd693',
    messagingSenderId: '93036228074',
    projectId: 'claravita-b3dea',
    authDomain: 'claravita-b3dea.firebaseapp.com',
    storageBucket: 'claravita-b3dea.firebasestorage.app',
    measurementId: 'G-VYX7JV0PXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPLMPCilbZ_iSr9pTm5_WqXVfS1b-nLwY',
    appId: '1:93036228074:android:6239c8cf4256b1fe3fd693',
    messagingSenderId: '93036228074',
    projectId: 'claravita-b3dea',
    storageBucket: 'claravita-b3dea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBohZ78YrLqGWmFRdgmsLOs_Llylfs5mGk',
    appId: '1:93036228074:ios:ce36c6786bccf4363fd693',
    messagingSenderId: '93036228074',
    projectId: 'claravita-b3dea',
    storageBucket: 'claravita-b3dea.firebasestorage.app',
    iosClientId: '93036228074-oq8cv7kj432stv6974q0l8r12rraha0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.claraVita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBohZ78YrLqGWmFRdgmsLOs_Llylfs5mGk',
    appId: '1:93036228074:ios:ce36c6786bccf4363fd693',
    messagingSenderId: '93036228074',
    projectId: 'claravita-b3dea',
    storageBucket: 'claravita-b3dea.firebasestorage.app',
    iosClientId: '93036228074-oq8cv7kj432stv6974q0l8r12rraha0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.claraVita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoVQ4DzNakx1pNU9BgdnPhTO5oUMfvh58',
    appId: '1:93036228074:web:4d8afc455cc6c9e63fd693',
    messagingSenderId: '93036228074',
    projectId: 'claravita-b3dea',
    authDomain: 'claravita-b3dea.firebaseapp.com',
    storageBucket: 'claravita-b3dea.firebasestorage.app',
    measurementId: 'G-SLKZ4SJNW9',
  );
}
